from typing import Protocol


class SecretStore(Protocol):
    async def get_secret(self, secret_name: str, tenant_scope: dict[str, str]) -> str: ...
    async def put_secret(
        self, secret_name: str, plaintext: str, tenant_scope: dict[str, str]
    ) -> None: ...
    async def delete_secret(self, secret_name: str, tenant_scope: dict[str, str]) -> None: ...
    async def health_check(self) -> None: ...
    async def start_cache_invalidation_listener(self) -> None: ...
    async def close(self) -> None: ...
