from typing import Protocol

from app.secrets.mcp_names import McpSecretOwnerType


class SecretStore(Protocol):
    async def get_secret(self, secret_name: str, tenant_scope: dict[str, str]) -> str: ...
    async def put_secret(
        self, secret_name: str, plaintext: str, tenant_scope: dict[str, str]
    ) -> None: ...
    async def delete_secret(self, secret_name: str, tenant_scope: dict[str, str]) -> None: ...
    async def count_mcp_secrets(
        self,
        workspace_id: str,
        *,
        server_id: str | None = None,
        owner_type: McpSecretOwnerType | None = None,
        owner_id: str | None = None,
    ) -> int: ...
    async def purge_mcp_secrets(
        self,
        workspace_id: str,
        *,
        server_id: str | None = None,
        owner_type: McpSecretOwnerType | None = None,
        owner_id: str | None = None,
    ) -> int: ...
    async def count_all_mcp_user_secrets(self) -> int: ...
    async def count_all_mcp_installation_secrets(self) -> int: ...
    async def purge_all_mcp_user_secrets(self) -> int: ...
    async def count_generated_catalog_secrets(self, workspace_id: str) -> int: ...
    async def purge_generated_catalog_secrets(self, workspace_id: str) -> int: ...
    async def health_check(self) -> None: ...
    async def start_cache_invalidation_listener(self) -> None: ...
    async def close(self) -> None: ...
