"""Create the complete greenfield gateway schema.

Revision ID: a10047518e6a
Revises:

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a10047518e6a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gateway_approval_receipt_uses",
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "claimed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_gateway_approval_receipt_uses_expires_at"),
        "gateway_approval_receipt_uses",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "gateway_catalog_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=False),
        sa.Column("auth_type", sa.String(), nullable=False),
        sa.Column("auth_secret_name", sa.String(), nullable=True),
        sa.Column("auth_header_name", sa.String(), nullable=True),
        sa.Column("network_route", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("management_mode", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "display_name", name="uq_gateway_catalog_source_name"),
    )
    op.create_index(
        "ix_gateway_catalog_sources_workspace",
        "gateway_catalog_sources",
        ["workspace_id", "enabled"],
        unique=False,
    )
    op.create_table(
        "gateway_mcp_servers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("server_name", sa.String(), nullable=False),
        sa.Column("server_url", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("auth_type", sa.String(), nullable=False),
        sa.Column("auth_header_name", sa.String(), nullable=True),
        sa.Column("auth_header_prefix", sa.String(), nullable=True),
        sa.Column(
            "public_headers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("credential_mode", sa.String(), nullable=False),
        sa.Column("credential_transitioning", sa.Boolean(), nullable=False),
        sa.Column("catalog_source_id", sa.UUID(), nullable=True),
        sa.Column("catalog_artifact_name", sa.String(), nullable=True),
        sa.Column("catalog_version", sa.String(), nullable=True),
        sa.Column("catalog_digest", sa.String(), nullable=True),
        sa.Column("catalog_imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provenance_type", sa.String(), nullable=False),
        sa.Column(
            "endpoint_configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "target_constraints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("connection_status", sa.String(), nullable=False),
        sa.Column("last_discovery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_discovery_error", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "credential_mode IN ('none','workspace','individual')",
            name="ck_gateway_mcp_servers_credential_mode",
        ),
        sa.CheckConstraint(
            "provenance_type IN ('manual','catalog','builtin')",
            name="ck_gateway_mcp_servers_provenance_type",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workspace_id", name="uq_gateway_mcp_servers_id_workspace"),
        sa.UniqueConstraint(
            "workspace_id",
            "scope_type",
            "target_id",
            "server_name",
            name="uq_gateway_mcp_servers_ws_target_name",
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "scope_type",
            "target_id",
            "server_url",
            name="uq_gateway_mcp_servers_ws_target_url",
        ),
    )
    op.create_index(
        "ix_gateway_mcp_servers_workspace_target",
        "gateway_mcp_servers",
        ["workspace_id", "target_id"],
        unique=False,
    )
    op.create_index(
        "uq_gateway_mcp_servers_builtin_destination",
        "gateway_mcp_servers",
        ["workspace_id", "scope_type", "target_id", "target_type"],
        unique=True,
        postgresql_where=sa.text("provenance_type='builtin'"),
        sqlite_where=sa.text("provenance_type='builtin'"),
    )
    op.create_table(
        "gateway_secrets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "tenant_scope",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("secret_name", sa.String(), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("aad", sa.LargeBinary(), nullable=False),
        sa.Column("key_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "gateway_catalog_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("artifact_kind", sa.String(), nullable=False),
        sa.Column("adapter_type", sa.String(), nullable=False),
        sa.Column("adapter_base_path", sa.String(), nullable=False),
        sa.Column("sync_status", sa.String(), nullable=False),
        sa.Column("last_sync_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_error", sa.String(), nullable=True),
        sa.Column("sync_cursor", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["gateway_catalog_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "artifact_kind", name="uq_gateway_catalog_binding_kind"),
    )
    op.create_index(
        "ix_gateway_catalog_bindings_source",
        "gateway_catalog_bindings",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "gateway_mcp_connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("owner_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "verified_tool_names",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(owner_type = 'installation' AND owner_id = 'installation') OR "
            "(owner_type = 'user' AND length(owner_id) > 0)",
            name="ck_gateway_mcp_connection_owner_id",
        ),
        sa.CheckConstraint(
            "owner_type IN ('installation', 'user')", name="ck_gateway_mcp_connection_owner_type"
        ),
        sa.CheckConstraint(
            "status IN ('connected', 'error')", name="ck_gateway_mcp_connection_status"
        ),
        sa.CheckConstraint(
            "error_code IS NULL OR length(error_code) <= 64",
            name="ck_gateway_mcp_connection_error_code",
        ),
        sa.ForeignKeyConstraint(
            ["server_id", "workspace_id"],
            ["gateway_mcp_servers.id", "gateway_mcp_servers.workspace_id"],
            name="fk_gateway_mcp_connection_server_workspace",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "server_id", "owner_type", "owner_id", name="uq_gateway_mcp_connection_owner"
        ),
    )
    op.create_index(
        "ix_gateway_mcp_connections_workspace_owner",
        "gateway_mcp_connections",
        ["workspace_id", "owner_type", "owner_id"],
        unique=False,
    )
    op.create_table(
        "gateway_tools",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("server_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("mcp_server_url", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column(
            "input_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "output_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("artifact_policy", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("capability", sa.String(), nullable=False),
        sa.Column("review_state", sa.String(), nullable=False),
        sa.Column("risk_level", sa.String(), nullable=False),
        sa.Column("auto_allowed", sa.Boolean(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("timeout_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["server_id"], ["gateway_mcp_servers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("server_id", "tool_name", name="uq_gateway_tools_ws_target_name"),
    )
    op.create_index(
        "ix_gateway_tools_workspace_target",
        "gateway_tools",
        ["workspace_id", "target_id"],
        unique=False,
    )
    op.create_table(
        "gateway_catalog_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("binding_id", sa.UUID(), nullable=False),
        sa.Column("artifact_kind", sa.String(), nullable=False),
        sa.Column("artifact_name", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "payload_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("compatible", sa.Boolean(), nullable=False),
        sa.Column("incompatibility_reason", sa.String(), nullable=True),
        sa.Column(
            "remote_endpoints",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("upstream_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["binding_id"], ["gateway_catalog_bindings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["source_id"], ["gateway_catalog_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "binding_id", "artifact_name", "version", name="uq_gateway_catalog_artifact_version"
        ),
    )
    op.create_index(
        "ix_gateway_catalog_artifacts_workspace_kind",
        "gateway_catalog_artifacts",
        ["workspace_id", "artifact_kind", "artifact_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_gateway_catalog_artifacts_workspace_kind", table_name="gateway_catalog_artifacts"
    )
    op.drop_table("gateway_catalog_artifacts")
    op.drop_index("ix_gateway_tools_workspace_target", table_name="gateway_tools")
    op.drop_table("gateway_tools")
    op.drop_index(
        "ix_gateway_mcp_connections_workspace_owner", table_name="gateway_mcp_connections"
    )
    op.drop_table("gateway_mcp_connections")
    op.drop_index("ix_gateway_catalog_bindings_source", table_name="gateway_catalog_bindings")
    op.drop_table("gateway_catalog_bindings")
    op.drop_table("gateway_secrets")
    op.drop_index(
        "uq_gateway_mcp_servers_builtin_destination",
        table_name="gateway_mcp_servers",
        postgresql_where=sa.text("provenance_type='builtin'"),
        sqlite_where=sa.text("provenance_type='builtin'"),
    )
    op.drop_index("ix_gateway_mcp_servers_workspace_target", table_name="gateway_mcp_servers")
    op.drop_table("gateway_mcp_servers")
    op.drop_index("ix_gateway_catalog_sources_workspace", table_name="gateway_catalog_sources")
    op.drop_table("gateway_catalog_sources")
    op.drop_index(
        op.f("ix_gateway_approval_receipt_uses_expires_at"),
        table_name="gateway_approval_receipt_uses",
    )
    op.drop_table("gateway_approval_receipt_uses")
    # ### end Alembic commands ###
