from enum import StrEnum


class ErrorCode(StrEnum):
    # Auth errors
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    INVALID_TOKEN = "INVALID_TOKEN"

    # Validation errors
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"

    # LLM errors
    PROVIDER_ERROR = "PROVIDER_ERROR"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"

    # Tool errors
    TOOL_NOT_ALLOWED = "TOOL_NOT_ALLOWED"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_ARGS_INVALID = "TOOL_ARGS_INVALID"
    TOOL_TIMEOUT = "TOOL_TIMEOUT"
    TOOL_BACKEND_UNAVAILABLE = "TOOL_BACKEND_UNAVAILABLE"
    TOOL_EXECUTION_FAILED = "TOOL_EXECUTION_FAILED"

    # General errors
    RATE_LIMITED = "RATE_LIMITED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
